### ISSUE TITLE
AttributeError: module 'dill._dill' has no attribute 'stack' 

### ISSUE THREAD

**Issue by lizhaohuigit1** [uqfoundation/dill#489]
AttributeError: module 'dill._dill' has no attribute 'stack'

**Comment by anivegesana** [comment]
Do you have some code that can reproduce the issue or do you need 'stack' to remain in dill? 'stack' was removed in dill 0.3.5 because it was used to pickle `super` but is no longer used because inner functions are more correctly handled.

**Comment by lizhaohuigit1** [comment]
> 

Thank you, I downgraded the dill version to 3.4.0 and the code ran successfully

**Comment by lizhaohuigit1** [comment]
> Do you have some code that can reproduce the issue or do you need 'stack' to remain in dill? 'stack' was removed in dill 0.3.5 because it was used to pickle `super` but is no longer used because inner functions are more correctly handled.

Thank you, I changed the dill version to 0.3.4 and the code ran successfully

**Comment by anivegesana** [comment]
Are you accessing `stack` directly in your code? It is possible to rewrite it so it doesn't use `stack` so it will work on dill 0.3.5. If you aren't using `stack` directly, that is a bug which we would like to fix.

**Comment by lizhaohuigit1** [comment]
> Are you accessing `stack` directly in your code? It is possible to rewrite it so it doesn't use `stack` so it will work on dill 0.3.5. If you aren't using `stack` directly, that is a bug which we would like to fix.

Here is my traceback:
File "train.py", line 600, in <module>
    main()
  File "train.py", line 461, in main
    train_dataset = datasets["train"].map(
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1244, in map
    return self._map_single(
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 157, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/fingerprint.py", line 157, in wrapper
    kwargs[fingerprint_name] = update_fingerprint(
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/fingerprint.py", line 105, in update_fingerprint
    hasher.update(transform_args[key])
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/fingerprint.py", line 57, in update
    self.m.update(self.hash(value).encode("utf-8"))
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/fingerprint.py", line 53, in hash
    return cls.hash_default(value)
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/fingerprint.py", line 46, in hash_default
    return cls.hash_bytes(dumps(value))
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 389, in dumps
    dump(obj, file)
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 361, in dump
    Pickler(file, recurse=True).dump(obj)
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/dill/_dill.py", line 620, in dump
    StockPickler.dump(self, obj)
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/lizhaohui/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 531, in save_function
    if id(obj) in dill._dill.stack:
AttributeError: module 'dill._dill' has no attribute 'stack'

**Comment by anivegesana** [comment]
Known issue. Update datasets and it should be fixed.

Duplicate of huggingface/datasets #4379

**Comment by lizhaohuigit1** [comment]
> ~Known issue. Update datasets and it should be fixed.~
> 
> Updating datasets clears the cache, which may not be desirable since it will take a long time to reload all of the datasets you have downloaded. Downgrading dill might be the reasonable option for you.
> 
> Duplicate of [huggingface/datasets#4379](https://github.com/huggingface/datasets/issues/4379)

ok,thanks.

**Comment by mmckerns** [comment]
This is a particular case of `datasets` using some `dill` internals directly.  While we try not to change internals, there is no guarantee. @lizhaohuigit1: I'm going to close this, but please do reopen or comment here if there's more to discuss.
